spring:
  application:
    name: reservation-api
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jackson:
    mapper:
      accept-case-insensitive-enums: true

server:
  servlet:
    context-path: /reservation/v1

api:
  security:
    token:
      secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG